name: CI

on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.1
          php_extensions: "bcmath"

      - name: Check formatting
        run: ./vendor/bin/ecs check

      - name: Run tests
        uses: php-actions/phpunit@v3
        with:
          version: 8.5
          php_version: 8.1
