name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: PHP Composer
      uses: php-actions/composer@v6
      with:
        php_version: 8.1
        php_extensions: "bcmath"
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        version: 8.5
        php_version: 8.1
